### ISSUE TITLE
Typo in institute label "GIDAZE"?

### ISSUE THREAD

**Issue by TristanHehnen** [MaCFP/matl-db#100]
Hi!

I just realised that there is a difference in the labeling of the GIDAZE+ files. All files and the respective directory are labeled "GIDAZE+", while in the [README ](https://github.com/MaCFP/matl-db/tree/master/Non-charring/PMMA/GIDAZE%2B) the label in the heading is "GIHAZE+". 
Which one is the correct one?

Best,
Tristan

**Comment by TristanHehnen** [comment]
There is a similar issue with [HKPoly](https://github.com/MaCFP/matl-db/tree/master/Non-charring/PMMA/HKPoly): The label in the README header and the directory name are "HKPoly" and the experiment/file labels are "HKPolyU".

**Comment by leventon** [comment]
GIDAZE is a possible typo from one of the original emails in which data was
sent over. We kept that with our naming convention.

I updated the readme to be GIHAZE, which was noted as the correct acronym
this summer (and in the readme is now spelled out as a collaboration of
three groups working together imperial college london, University of
Cantabria, and reax engineering).

However, I did not rename all of the individual files and because (a) I did
not want to go through with that at the time and (b) my most recent email
from the PI from that group wrote GIDAZE. I would push them for some
consistency here in naming, but before I focus my efforts on that I have
already made multiple requests for a review of their experimental
measurements for a parent inconsistencies in their data period that is what
I really want to update from them first. That's more important.

As for Hong Kong polytechnic, it's probably easiest to just remove the "u".
If you would like to trim that, that would be great for consistency.

**Comment by TristanHehnen** [comment]
Well, if it is mainly an issue of someone needs to put in the time to change the names for HKPoly, then I could do it. 

For GIDAZE it might be best then to make sure first what label it should be, then I could change them as well.

**Comment by leventon** [comment]
If you would like to take the lead on renaming, I would appreciate it. I
suspect GIHAZE is the correct spelling, as that group includes the hazeLab
at Imperial College. Again, I have received both spellings from the pi of
that group, but at least they will be consistent if we stay with one.

**Comment by TristanHehnen** [comment]
HKPoly: see commit.

GIDAZE/GIHAZE: I guess it is GIDAZE then.
